name: TheChase
channels:
  - defaults
dependencies:
  - python=3.13
  - plotly
  - streamlit
  - seaborn
  - matplotlib
  - pandas
  - sqlalchemy
  - numpy
  - pip
  - pip:
      - streamlit-authenticator
prefix: /usr/local/Caskroom/miniconda/base/envs/TheChase
