name: TheChase
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - alembic=1.18.4=pyhcf101f3_0
  - altair=6.0.0=pyhd8ed1ab_1
  - astor=0.8.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.7.22=hb04b931_10
  - aws-c-cal=0.7.1=hd73d8db_1
  - aws-c-common=0.9.23=hfdf4475_0
  - aws-c-compression=0.2.18=hd73d8db_7
  - aws-c-event-stream=0.4.2=h2713d70_15
  - aws-c-http=0.8.2=he29c2fd_6
  - aws-c-io=0.14.10=h4406d91_1
  - aws-c-mqtt=0.10.4=hf6997d9_8
  - aws-c-s3=0.6.0=h13137a3_2
  - aws-c-sdkutils=0.1.16=hd73d8db_3
  - aws-checksums=0.1.18=hd73d8db_7
  - aws-crt-cpp=0.27.3=h0a15bd7_2
  - aws-sdk-cpp=1.11.329=h554caeb_9
  - base58=2.1.1=pyhd8ed1ab_1
  - bcrypt=5.0.0=py311hd2a4513_1
  - blinker=1.9.0=pyhff2d567_0
  - boto3=1.42.54=pyhd8ed1ab_0
  - botocore=1.42.54=pyhd8ed1ab_0
  - brotli=1.1.0=h1c43f85_4
  - brotli-bin=1.1.0=h1c43f85_4
  - brotli-python=1.1.0=py311h7b20566_4
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311h26bcf6e_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - contourpy=1.3.3=py311h9d13916_4
  - cycler=0.12.1=pyhcf101f3_2
  - fonttools=4.61.1=py311he13f9b5_0
  - freetype=2.14.1=h694c41f_0
  - gflags=2.2.2=hac325c4_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - glog=0.7.1=h2790a97_0
  - greenlet=3.3.2=py311hc3ea09e_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jmespath=1.1.0=pyhcf101f3_1
  - jpeg=9e=hb7f2c08_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kiwisolver=1.4.9=py311h591569d_2
  - krb5=1.22.2=h207b36a_0
  - lcms2=2.15=h29502cd_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20240116.2=cxx17_hf036a51_1
  - libarrow=13.0.0=h6d820dd_49_cpu
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.18.0=h9a2545f_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.17=hac1461d_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.4=h991f03e_0
  - libffi=3.5.2=hd1f9c09_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_18
  - libgfortran=15.2.0=h7e5c614_18
  - libgfortran5=15.2.0=hd16e46c_18
  - libgoogle-cloud=2.26.0=h721cda5_0
  - libgoogle-cloud-storage=2.26.0=h9e84e37_0
  - libgrpc=1.62.2=h384b2fc_0
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.2=h11316ed_0
  - liblzma-devel=5.8.2=h11316ed_0
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libpng=1.6.55=h07817ec_0
  - libprotobuf=4.25.3=hd4aba4c_1
  - libre2-11=2023.09.01=h81f5012_2
  - libsqlite=3.51.2=hb99441e_0
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.19.0=h064b379_1
  - libtiff=4.5.0=hee9004a_2
  - libutf8proc=2.8.0=he670073_1
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.13=h0d85af4_1004
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.7=ha54dae1_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py311he13f9b5_0
  - matplotlib=3.10.8=py311h6eed73b_0
  - matplotlib-base=3.10.8=py311h48d7e91_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.17.0=pyhcf101f3_0
  - ncurses=6.5=h923df54_0
  - numpy=1.26.4=py311hc43a94b_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.6.1=hb6871ef_1
  - orc=2.0.1=hf43e91b_1
  - packaging=26.0=pyhcf101f3_0
  - pandas-stubs=2.2.3.250308=py311hecd8cb5_0
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=9.4.0=py311h5bae705_1
  - pip=26.0.1=pyhc872135_0
  - plotly=6.5.2=pyhd8ed1ab_0
  - protobuf=4.25.3=py311h6b31176_1
  - pthread-stubs=0.4=h00291cd_1002
  - pyarrow=13.0.0=py311h23c41e2_49_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pympler=1.1=pyhd8ed1ab_1
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h74c2667_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311h53ebfaf_1
  - qhull=2020.2=h3c5361c_5
  - re2=2023.09.01=hb168e87_2
  - readline=8.3=h49f2429_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rpds-py=0.30.0=py311hd2a4513_0
  - s3transfer=0.16.0=pyhd8ed1ab_0
  - scipy=1.17.1=py311h556693a_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - semver=3.0.4=pyhcf101f3_1
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h01f5ddf_1
  - sqlalchemy=2.0.46=py311ha332486_1
  - statsmodels=0.14.6=py311ha837bc1_0
  - tk=8.6.13=h7142dee_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py311ha2bb86f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - unicodedata2=17.0.1=py311hc71d4c3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - validators=0.35.0=pyhd8ed1ab_0
  - watchdog=6.0.0=py311hf197a57_2
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xz=5.8.2=h8df612c_0
  - xz-gpl-tools=5.8.2=h8df612c_0
  - xz-tools=5.8.2=h11316ed_0
  - yaml=0.2.5=h4132b18_3
  - zipp=3.23.0=pyhcf101f3_1
  - zstandard=0.25.0=py311h62e9434_1
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - cachetools==6.2.6
      - captcha==0.7.1
      - cryptography==46.0.5
      - dotenv==0.9.9
      - extra-streamlit-components==0.1.81
      - pandas==2.3.3
      - psycopg2-binary==2.9.11
      - pyjwt==2.11.0
      - pytz==2025.2
      - streamlit==1.54.0
      - streamlit-authenticator==0.4.2
      - tenacity==9.1.4
      - tzdata==2025.3
prefix: /usr/local/Caskroom/miniconda/base/envs/TheChase
