name: TheChase
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - plotly
  - streamlit
  - seaborn
  - matplotlib
  - pandas
  - sqlalchemy
  - numpy
  - pip
  - alembic
  - pip:
      - streamlit-authenticator
      - psycopg2
      - python-dotenv
prefix: /usr/local/Caskroom/miniconda/base/envs/TheChase
